#!/usr/bin/env bash
# Using what you did with 1-install_nginx_web_server
# write 3-redirection so that it configures a brand new Ubuntu machine
# Requirements asked in this task

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.blog.ehoneahobed.com permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart