#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 20 and
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration

x=1
while [ $x -lt 21 ] 
do
	if [ $x -eq 4 ]
	then
		echo $x
		echo "bad luck from China"
	elif [ $x -eq 9 ]
	then
		echo $x
		echo "bad luck from Japan"
	elif [ $x -eq 17 ]
	then
		echo $x
		echo "bad luck from Italy"
	else
		echo $x
	fi
	((x++))
done
